# Generated by Django 5.0.1 on 2024-04-20 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_registermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginModel',
        ),
    ]
