# Generated by Django 5.0.1 on 2024-04-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_loginmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='username',
            field=models.CharField(default='guest', max_length=30, unique=True),
        ),
    ]
